FROM node:8.14.0-alpine
WORKDIR /nlan-user-front
COPY . .
RUN set -ex && \
	apk add git && \
	npm install && \
	rm -rf /var/cache/apk

COPY postcss.config.js  node_modules/element-ui/lib/theme-chalk/
COPY postcss.config.js /src/styles/
COPY postcss.config.js  node_modules/
